version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    env_file: 
      - .env
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs # Логи будут сохраняться на хосте
    command: npm start

  mongo:
    image: mongo:6
    container_name: telegram_bot_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data: